# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d5fa010ad48a02ff153afa4b5451f430969c9af3e5fe95c0255d6782afbc6ad0d33c0d79a21fd84410948611860f11c46b38b403b3a30dd6779a1007ffd2cf

test:
  secret_key_base: 3e2509fad3431d97aa05beaa00ba3d992d320b8844a2f8aa92a4b9da4869f015ae47da09879b8097c44bb5cfad7ae9a51a9152379c63c8a3dade9e35d8975e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
